version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "7000:7000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydatabase
      - RUST_LOG=debug

  frontend:
    build:
      context: ./frontend
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"