[package]
name = "hello"
version = "0.0.0"
workspace = "../"
edition = "2021"
publish = false

[dependencies]
rocket = "0.5.1"
diesel = { version = "2.2.0", features = ["postgres", "chrono"] }
dotenvy = "0.15"
chrono = "0.4"